FROM python:3.12-slim

# Crear carpeta de trabajo
WORKDIR /app

# Copia de requerimientos
COPY requirements.txt .

# Instalarlos
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY ./app ./app

# Exponer el puerto
EXPOSE 5000

# Comandos para ejecutar FastAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]